import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const sheetId: string = "1TW41_iMkvCvsqjedB7XLEUiP8uUGnAJp";
    const base = `https://docs.google.com/spreadsheets/d/${sheetId}/gviz/tq?`;
    const sheetName = "Plan";
    const query = encodeURIComponent("Select *");
    const url = `${base}&sheet=${sheetName}&tq=${query}`;
    const [message, setMessage] = useState<string>();

    const getData = () => {
        const excercices: string[][] = [];
        let actualDay: string[] = [];
        fetch(url)
            .then((res) => res.text())
            .then((rep) => {
                const minData = JSON.parse(
                    rep.substring(47).slice(0, -2)
                ).table.rows.slice(8);
                minData.filter((x: any, index: number) => {
                    const field = x.c[2]?.v;
                    if (field.includes("Ejercicio")) {
                        excercices.push(actualDay);
                        actualDay = [];
                    } else if (field !== "Registro") {
                        actualDay.push(field);
                        if (index === minData.length - 1) {
                            excercices.push(actualDay);
                        }
                    }
                });
                return excercices;
            });

        return excercices;
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <button onClick={getData}>GET DATA</button>
                {message ? <p>{message}</p> : null}
            </main>
        </>
    );
}
